language: node_js
# nodejs版本
node_js: 
    - '10'

cache:
  directories:
    - node_modules

install:
  - npm install

before_script:

script:
  - npm run build

branches:
  only:
    - master
env:
 global:

deploy:
  local_dir: public
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master